name: "Setup Linux Testing Environment"
description: "Sets up complete Linux environment with Python, CUDA, vcpkg, and CMake for testing and development"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.11"
    type: string
  setup-path:
    description: "Path to setup.py or pyproject.toml for project installation"
    required: false
    default: "./"
    type: string
  dev-requirements:
    description: "Path to development requirements file"
    required: false
    default: "./scripts/configs/dev_requirements.txt"
    type: string
  install-project:
    description: "Whether to install the project itself"
    required: false
    default: "true"
    type: string
  extra-packages:
    description: "Additional packages to install (space-separated)"
    required: false
    type: string
  checkout:
    description: "Whether to checkout the repository"
    required: false
    default: "true"
    type: string
  # CUDA inputs
  enable-cuda:
    description: "Whether to install CUDA toolkit"
    required: false
    default: "true"
    type: string
  cuda-version:
    description: "CUDA version to install"
    required: false
    default: "12.6.0"
    type: string
  # vcpkg inputs
  enable-vcpkg:
    description: "Whether to setup vcpkg"
    required: false
    default: "true"
    type: string
  vcpkg-commit:
    description: "vcpkg commit ID to checkout"
    required: false
    default: "15fd3bbcf7cc66249ba11f87a6215ee6f291bb26"
    type: string
  vcpkg-install-path:
    description: "vcpkg installation path"
    required: false
    default: "/tmp/vcpkg"
    type: string
  # Cleanup inputs
  enable-cleanup:
    description: "Whether to free up disk space"
    required: false
    default: "true"
    type: string
  cleanup-aggressive:
    description: "Perform aggressive cleanup"
    required: false
    default: "false"
    type: string

outputs:
  python-path:
    description: "Path to Python executable"
    value: ${{ steps.python-setup.outputs.python-path }}
  pip-cache-dir:
    description: "Pip cache directory"
    value: ${{ steps.python-setup.outputs.cache-dir }}
  cuda-path:
    description: "Path to CUDA installation"
    value: ${{ steps.cuda-setup.outputs.cuda-path }}
  vcpkg-root:
    description: "Path to vcpkg root"
    value: ${{ steps.vcpkg-setup.outputs.vcpkg-root }}
  cmake-toolchain:
    description: "Path to CMake toolchain file"
    value: ${{ steps.vcpkg-setup.outputs.cmake-toolchain }}
  build-path:
    description: "Path to CMake build directory"
    value: ${{ steps.cmake-build.outputs.build-path }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: inputs.checkout == 'true'
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Free up disk space
      if: inputs.enable-cleanup == 'true'
      uses: ./.github/actions/cleanup/free-disk-space
      with:
        platform: linux
        aggressive: ${{ inputs.cleanup-aggressive }}

    - name: Set up Python environment
      id: python-setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup CUDA
      if: inputs.enable-cuda == 'true'
      id: cuda-setup
      uses: Jimver/cuda-toolkit@v0.2.24
      with:
        cuda: ${{ inputs.cuda-version }}

    - name: Setup vcpkg
      if: inputs.enable-vcpkg == 'true'
      id: vcpkg-setup
      uses: ./.github/actions/setup/vcpkg
      with:
        vcpkg-commit: ${{ inputs.vcpkg-commit }}
        platform: linux
        install-path: ${{ inputs.vcpkg-install-path }}

    - name: Logs
      run: |
        echo "   Root: $VCPKG_ROOT"
        echo "   Toolchain: $CMAKE_TOOLCHAIN"

    - name: Install vcpkg dependencies
      if: inputs.enable-vcpkg == 'true'
      shell: bash
      run: |
        if [ -f "src/vcpkg.json" ]; then
          echo "=== Installing vcpkg dependencies from src/vcpkg.json ==="
          cd src
          ${{ steps.vcpkg-setup.outputs.vcpkg-root }}/vcpkg install --recurse
          cd ..
          echo "vcpkg dependencies installed successfully"
        else
          echo "Warning: src/vcpkg.json not found, skipping vcpkg dependencies installation"
        fi

    - name: Install Python dependencies and project
      id: python-deps
      shell: bash
      run: |
        echo "Upgrading pip and build tools..."
        python -m pip install --upgrade pip build setuptools wheel

        if [ "${{ inputs.install-project }}" = "true" ]; then
          if [ -f "${{ inputs.setup-path }}/pyproject.toml" ]; then
            echo "Installing project from pyproject.toml at ${{ inputs.setup-path }}..."
            python -m pip install ${{ inputs.setup-path }} --config-settings=cmake.args="-S;src;--preset;linux-x86_64-Release"
          else
            echo "Warning: No pyproject.toml found at ${{ inputs.setup-path }}"
          fi
        fi

        # Install development requirements if file exists
        if [ -f "${{ inputs.dev-requirements }}" ]; then
          echo "Installing development requirements from ${{ inputs.dev-requirements }}..."
          python -m pip install -r ${{ inputs.dev-requirements }}
        else
          echo "Warning: Development requirements file not found at ${{ inputs.dev-requirements }}"
        fi

        # Install extra packages if provided
        if [ -n "${{ inputs.extra-packages }}" ]; then
          echo "Installing extra packages: ${{ inputs.extra-packages }}..."
          python -m pip install ${{ inputs.extra-packages }}
        fi

        # Set outputs
        PYTHON_PATH=$(which python)
        CACHE_DIR=$(python -m pip cache dir 2>/dev/null || echo "")

    - name: Display environment info
      shell: bash
      run: |
        echo "=== Environment Information ==="
        echo "Python version: $(python --version)"
        echo "Python executable: $(which python)"
        echo "Pip version: $(pip --version)"
        echo "Installed Python packages:"
        pip list | head -20

        if [ "${{ inputs.enable-cuda }}" = "true" ]; then
          echo "=== CUDA Information ==="
          if command -v nvcc &> /dev/null; then
            echo "NVCC version: $(nvcc --version | grep -o 'release [0-9]*\.[0-9]*' || echo 'Not found')"
            echo "CUDA path: ${{ steps.cuda-setup.outputs.cuda-path || 'Not set' }}"
          else
            echo "CUDA not found in PATH"
          fi
        fi

        if [ "${{ inputs.enable-vcpkg }}" = "true" ]; then
          echo "=== vcpkg Information ==="
          echo "vcpkg root: ${{ steps.vcpkg-setup.outputs.vcpkg-root || 'Not set' }}"
          echo "CMake toolchain: ${{ steps.vcpkg-setup.outputs.cmake-toolchain || 'Not set' }}"
        fi

        if [ "${{ inputs.enable-cmake-build }}" = "true" ]; then
          echo "=== CMake Build Information ==="
          echo "Build path: ${{ steps.cmake-build.outputs.build-path || 'Not set' }}"
          if command -v cmake &> /dev/null; then
            echo "CMake version: $(cmake --version | head -1)"
          fi
        fi

        echo "=== System Information ==="
        uname -a
        echo "Available disk space:"
        df -h / || true
        echo "CPU info:"
        nproc
        lscpu | head -5 || true
