name: Set Runner

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch name to check (optional - will auto-detect if not provided)"
        required: false
        type: string
      branch_pattern:
        description: "Regex pattern to match against branch names for self-hosted runner (default: 'test-workflow')"
        required: false
        type: string
    outputs:
      runner:
        description: "The runner to use for jobs (self-hosted or ubuntu-latest)"
        value: ${{ jobs.set-runner.outputs.runner }}
      is_self_hosted:
        description: "Boolean indicating if self-hosted runner should be used"
        value: ${{ jobs.set-runner.outputs.is_self_hosted }}

jobs:
  set-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.determine-runner.outputs.runner }}
      is_self_hosted: ${{ steps.determine-runner.outputs.is_self_hosted }}
    steps:
      - name: Determine Runner
        id: determine-runner
        run: |
          # Use input branch if provided, otherwise detect from context
          if [ -n "${{ inputs.branch }}" ]; then
            BRANCH="${{ inputs.branch }}"
          else
            # Try different branch detection methods
            if [ -n "${{ github.head_ref }}" ]; then
              BRANCH="${{ github.head_ref }}"
            elif [ -n "${{ github.ref_name }}" ]; then
              BRANCH="${{ github.ref_name }}"
            else
              BRANCH="main"
            fi
          fi

          echo "Detected branch: $BRANCH"

          # Determine runner based on configurable branch pattern
          if [[ "$BRANCH" =~ ${{ inputs.branch_pattern || 'test-workflow' }} ]]; then
            RUNNER="self-hosted"
            IS_SELF_HOSTED="true"
            echo "✅ Using self-hosted runner for matching branch pattern"
          else
            RUNNER="ubuntu-latest"
            IS_SELF_HOSTED="false"
            echo "✅ Using GitHub-hosted runner for regular branch"
          fi

          # Set outputs
          echo "runner=$RUNNER" >> $GITHUB_OUTPUT
          echo "is_self_hosted=$IS_SELF_HOSTED" >> $GITHUB_OUTPUT

          # Also set environment variables for this job
          echo "RUNNER=$RUNNER" >> $GITHUB_ENV
          echo "IS_SELF_HOSTED=$IS_SELF_HOSTED" >> $GITHUB_ENV

          echo "Final runner selection: $RUNNER"
