name: "Build Python Wheels"
description: "Build Python wheels for versions 3.11, 3.12, and 3.13"

inputs:
  python-version:
    description: "Python version to build for"
    required: true

outputs:
  wheel-path:
    description: "Path to the built wheels"
    value: "dist/"
  version:
    description: "Version used for the build"
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install build dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools setuptools-scm

    - name: Build wheel for Python ${{ inputs.python-version }}
      shell: bash
      run: |
        echo "🔨 Building wheel for Python ${{ inputs.python-version }}"
        python -m build --wheel --outdir dist/
        echo "✅ Build complete:"
        ls -la dist/

    - name: Install wheel and test dependencies
      shell: bash
      run: |
        pip install dist/*.whl
        pip install pytest pytest-cov pytest-benchmark

    - name: Run tests (excluding benchmarks)
      shell: bash
      run: |
        echo "🧪 Running tests (excluding benchmarks)"
        pytest tests
