name: "Build and Publish Documentation"
description: "Build Sphinx documentation and publish to GitHub Pages"

inputs:
  python-version:
    description: "Python version to use for building documentation"
    required: true
    type: string
  doc-requirements:
    description: "Path to documentation requirements file"
    required: false
    default: "./docs/doc_requirements.txt"
    type: string

outputs:
  artifact-name:
    description: "Name of the uploaded documentation artifact"
    value: "github-pages"

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install documentation dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip

        echo "📦 Installing documentation requirements..."
        if [ -f "${{ inputs.doc-requirements }}" ]; then
          pip install -r ${{ inputs.doc-requirements }}
        fi

        echo "📦 Installing project..."
        pip install -e .

    - name: Build Sphinx documentation
      shell: bash
      run: |
        echo "📚 Building Sphinx documentation..."
        cd docs
        sphinx-build -b html . _build/html
        echo "✅ Documentation build complete"

    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
