name: Build and Publish Python Wheels

on: push

env:
  CUDA_VERSION: 12.5.0
  WHEEL_WORKING_DIR: "scripts/configs"
  WHEEL_OUT_DIR: "dist"
  GITHUB_REF: "refs/heads/main"
  CMAKE_TOOLCHAIN_FILE_PATH: "${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest]
        python-version: [3.13]
        arch: [x64]

    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"
          vcpkgGitCommitId: "15fd3bbcf7cc66249ba11f87a6215ee6f291bb26"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}

      - uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: "12.5.0"
          log-file-suffix: "${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.arch }}"

      - name: Verify CUDA installation
        run: nvcc --version

      - name: Set environment variables
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "ARCH=AMD64" >> $GITHUB_ENV
            echo "PRESET=windows-x86_64-Release" >> $GITHUB_ENV
            echo "CMAKE_TOOLCHAIN_FILE=${{ env.CMAKE_TOOLCHAIN_FILE_PATH }}" >> $GITHUB_ENV
          else
            echo "ARCH=x86_64" >> $GITHUB_ENV
            echo "PRESET=linux-x86_64-Release" >> $GITHUB_ENV
            echo "CMAKE_TOOLCHAIN_FILE=${{ env.CMAKE_TOOLCHAIN_FILE_PATH }}" >> $GITHUB_ENV
          fi

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel scikit-build-core nanobind twine

      - name: Build wheel
        working-directory: ${{ env.WHEEL_WORKING_DIR }}
        run: python -m pip wheel ./ -w ../../${{ env.WHEEL_OUT_DIR }}/ --config-settings=cmake.args="--preset;${{ env.PRESET }}" --config-settings=cmake.define.CMAKE_TOOLCHAIN_FILE="${{ env.CMAKE_TOOLCHAIN_FILE }}"

      - name: Publish wheel to Test PyPI
        if: github.ref == '${{ env.GITHUB_REF }}'
        run: python -m twine upload --repository testpypi ${{ env.WHEEL_OUT_DIR }}/*
