name: Publish to PyPI

on: push

env:
  CONFIG_DIR: ./scripts/configs
  SRC_REQUIREMENTS: ./scripts/configs/requirements.txt
  DOC_REQUIREMENTS: ./docs/doc_requirements.txt
  FINAL_DOC_REQUIREMENTS: ./docs/final_doc_requirements.txt
  PYTHON_VERSION: "3.11"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Upload to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST }}
        run: |
          twine upload --repository testpypi dist/*
